import { useListDocuments } from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { FileText, Download, Clock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { format } from "date-fns";

export default function Documents() {
  const { data: documents, isLoading } = useListDocuments();

  return (
    <div className="p-8 space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Generated Documents</h1>
          <p className="text-muted-foreground mt-2">Access phase completion certificates and audit reports.</p>
        </div>
      </div>

      {isLoading ? (
        <div className="space-y-4">
          {[1, 2, 3].map(i => <Skeleton key={i} className="h-24 w-full" />)}
        </div>
      ) : documents?.length === 0 ? (
        <Card className="flex flex-col items-center justify-center p-12 text-center bg-muted/50 border-dashed">
          <FileText className="h-12 w-12 text-muted-foreground mb-4" />
          <h3 className="text-lg font-semibold">No documents found</h3>
          <p className="text-muted-foreground mt-1">Documents will appear here once they are generated from completed phases.</p>
        </Card>
      ) : (
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {documents?.map(doc => (
            <Card key={doc.id} className="hover-elevate transition-all flex flex-col">
              <CardHeader className="pb-2">
                <CardTitle className="text-lg flex items-start gap-2">
                  <FileText className="w-5 h-5 text-primary flex-shrink-0 mt-0.5" />
                  <span className="line-clamp-2">{doc.title}</span>
                </CardTitle>
              </CardHeader>
              <CardContent className="flex-1 flex flex-col justify-between">
                <div className="space-y-2 mb-6">
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Phase ID</span>
                    <span className="font-medium">#{doc.phaseId}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Generated By</span>
                    <span className="font-medium">{doc.generatedBy}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Date</span>
                    <span className="font-medium flex items-center">
                      <Clock className="w-3 h-3 mr-1" />
                      {format(new Date(doc.generatedAt), 'MMM d, yyyy')}
                    </span>
                  </div>
                </div>
                
                <Button variant="outline" className="w-full" onClick={() => window.open(`/api/documents/${doc.id}/download`, '_blank')}>
                  <Download className="w-4 h-4 mr-2" />
                  Download PDF
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
