const colors = {
  light: {
    text: "#0f172a",
    tint: "#2563eb",
    background: "#f8fafc",
    foreground: "#0f172a",
    card: "#ffffff",
    cardForeground: "#0f172a",
    primary: "#2563eb",
    primaryForeground: "#ffffff",
    secondary: "#f1f5f9",
    secondaryForeground: "#0f172a",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    accent: "#eff6ff",
    accentForeground: "#1e40af",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e2e8f0",
    input: "#e2e8f0",
    success: "#10b981",
    successLight: "#ecfdf5",
    successBorder: "#a7f3d0",
    warning: "#f59e0b",
    warningLight: "#fffbeb",
    warningBorder: "#fde68a",
    error: "#ef4444",
    errorLight: "#fef2f2",
    errorBorder: "#fecaca",
  },
  radius: 10,
};

export default colors;
