export const PHOTO_IMAGES_FOLDER_ID          = "1xWO8A2fXJ7ztpzpt-iqUNg8Xjq6vX7a0";
export const PHOTO_IMAGES_2_STAMPED_FOLDER_ID = "18dMOuEuKFu_prnx9FW_FW1y2nFUebW6C";

export const PHOTO_SCAN_FOLDER_IDS = [
  PHOTO_IMAGES_FOLDER_ID,
  PHOTO_IMAGES_2_STAMPED_FOLDER_ID,
];
