import PDFDocument from "pdfkit";

export interface HandoverPhoto {
  photoId: string;
  cableLink: string | null;
  phaseLink: string | null;
  reqImgType: string | null;
  reqImgOrder: string | null;
  approval: string | null;
  label: string | null;
}

export interface HandoverReport {
  name: string;
  reportType: string;
  cable: string | null;
  string: string;
}

export interface HandoverPackInput {
  stringName: string;
  generatedBy: string;
  generatedAt: Date;
  photos: HandoverPhoto[];
  reports: HandoverReport[];
}

const BRAND_BLUE  = "#1e3a5f";
const BRAND_LIGHT = "#e8f0f8";
const GRAY_700    = "#374151";
const GRAY_400    = "#9ca3af";
const GREEN       = "#166534";
const GREEN_BG    = "#dcfce7";
const AMBER       = "#92400e";
const AMBER_BG    = "#fef3c7";
const RED         = "#991b1b";
const RED_BG      = "#fee2e2";

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
}

function approvalColor(a: string | null): { fg: string; bg: string } {
  const v = (a ?? "").toLowerCase();
  if (v === "approved" || v === "checked" || v === "verified") return { fg: GREEN, bg: GREEN_BG };
  if (v === "rejected") return { fg: RED, bg: RED_BG };
  return { fg: AMBER, bg: AMBER_BG };
}

export function generateHandoverPdf(input: HandoverPackInput): Buffer {
  const chunks: Buffer[] = [];
  const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true });
  doc.on("data", (c: Buffer) => chunks.push(c));

  const W = doc.page.width - 100; // usable width (margins 50 each side)

  // ── Cover page ────────────────────────────────────────────────────────────

  // Header band
  doc.rect(50, 50, W, 6).fill(BRAND_BLUE);
  doc.rect(50, 56, W, 2).fill("#3b82f6");

  doc.moveDown(2);

  doc.fontSize(26).fillColor(BRAND_BLUE).text("CVOW Installation Handover Pack", 50, 80, { width: W, align: "center" });
  doc.fontSize(18).fillColor(GRAY_700).text(`String ${input.stringName}`, 50, 118, { width: W, align: "center" });

  doc.fontSize(11).fillColor(GRAY_400).text(
    `Generated: ${formatDate(input.generatedAt)}   ·   Generated by: ${input.generatedBy}`,
    50, 150, { width: W, align: "center" },
  );

  // Summary boxes
  const boxY = 200;
  const boxW = (W - 20) / 3;
  const boxes = [
    { label: "Approved Photos", value: String(input.photos.length) },
    { label: "Field Reports", value: String(input.reports.length) },
    { label: "Cables / Towers", value: String(new Set(input.photos.map(p => p.cableLink).filter(Boolean)).size) },
  ];
  boxes.forEach((box, i) => {
    const x = 50 + i * (boxW + 10);
    doc.rect(x, boxY, boxW, 70).fillAndStroke(BRAND_LIGHT, BRAND_BLUE);
    doc.fontSize(28).fillColor(BRAND_BLUE).text(box.value, x, boxY + 10, { width: boxW, align: "center" });
    doc.fontSize(10).fillColor(GRAY_700).text(box.label, x, boxY + 46, { width: boxW, align: "center" });
  });

  doc.rect(50, boxY + 90, W, 1).fill(GRAY_400);

  // Purpose note
  doc.fontSize(10).fillColor(GRAY_700)
    .text(
      "This handover pack was automatically generated from the CVOW Installation Image Review System. " +
      "It summarises all approved installation photos and field reports for the string listed above.",
      50, boxY + 105, { width: W, align: "left" },
    );

  // ── Photo manifest ────────────────────────────────────────────────────────

  doc.addPage();

  doc.fontSize(16).fillColor(BRAND_BLUE).text("Approved Photo Manifest", 50, 50);
  doc.rect(50, 72, W, 2).fill(BRAND_BLUE);

  if (input.photos.length === 0) {
    doc.fontSize(10).fillColor(GRAY_400).text("No approved photos found for this string.", 50, 85);
  } else {
    const colWidths = [30, 150, 140, 120, 70];
    const colX = [50, 80, 230, 370, 490];
    const headers = ["#", "Cable / Tower", "Phase", "Image Type", "Approval"];

    let y = 82;

    const drawRowBg = (rowY: number, bg: string) => {
      doc.rect(50, rowY, W, 18).fill(bg);
    };

    // Header
    drawRowBg(y, BRAND_BLUE);
    headers.forEach((h, i) => {
      doc.fontSize(9).fillColor("white").text(h, colX[i] + 2, y + 5, { width: colWidths[i], lineBreak: false });
    });
    y += 18;

    input.photos.forEach((p, idx) => {
      if (y > doc.page.height - 80) {
        doc.addPage();
        y = 50;
        drawRowBg(y, BRAND_BLUE);
        headers.forEach((h, i) => {
          doc.fontSize(9).fillColor("white").text(h, colX[i] + 2, y + 5, { width: colWidths[i], lineBreak: false });
        });
        y += 18;
      }

      const rowBg = idx % 2 === 0 ? "#f9fafb" : "white";
      drawRowBg(y, rowBg);

      const { fg } = approvalColor(p.approval);

      doc.fontSize(8).fillColor(GRAY_700)
        .text(String(idx + 1),                    colX[0] + 2, y + 5, { width: colWidths[0], lineBreak: false })
        .text(p.cableLink ?? "—",                  colX[1] + 2, y + 5, { width: colWidths[1], lineBreak: false })
        .text(p.phaseLink ?? "—",                  colX[2] + 2, y + 5, { width: colWidths[2], lineBreak: false })
        .text(p.reqImgType ?? p.label ?? "—",      colX[3] + 2, y + 5, { width: colWidths[3], lineBreak: false });

      doc.fontSize(8).fillColor(fg)
        .text(p.approval ?? "Pending",             colX[4] + 2, y + 5, { width: colWidths[4], lineBreak: false });

      y += 18;
    });
  }

  // ── Reports section ───────────────────────────────────────────────────────

  doc.addPage();

  doc.fontSize(16).fillColor(BRAND_BLUE).text("Field Reports", 50, 50);
  doc.rect(50, 72, W, 2).fill(BRAND_BLUE);

  if (input.reports.length === 0) {
    doc.fontSize(10).fillColor(GRAY_400).text("No field reports found for this string.", 50, 85);
  } else {
    const colWidths = [120, 110, 280];
    const colX = [50, 170, 280];
    const headers = ["Cable / Tower", "Type", "Report Name"];

    let y = 82;

    const drawRowBg = (rowY: number, bg: string) => {
      doc.rect(50, rowY, W, 18).fill(bg);
    };

    drawRowBg(y, BRAND_BLUE);
    headers.forEach((h, i) => {
      doc.fontSize(9).fillColor("white").text(h, colX[i] + 2, y + 5, { width: colWidths[i], lineBreak: false });
    });
    y += 18;

    input.reports.forEach((r, idx) => {
      if (y > doc.page.height - 80) {
        doc.addPage();
        y = 50;
        drawRowBg(y, BRAND_BLUE);
        headers.forEach((h, i) => {
          doc.fontSize(9).fillColor("white").text(h, colX[i] + 2, y + 5, { width: colWidths[i], lineBreak: false });
        });
        y += 18;
      }
      const rowBg = idx % 2 === 0 ? "#f9fafb" : "white";
      drawRowBg(y, rowBg);

      doc.fontSize(8).fillColor(GRAY_700)
        .text(r.cable ?? r.string,  colX[0] + 2, y + 5, { width: colWidths[0], lineBreak: false })
        .text(r.reportType,          colX[1] + 2, y + 5, { width: colWidths[1], lineBreak: false })
        .text(r.name,                colX[2] + 2, y + 5, { width: colWidths[2], lineBreak: false });

      y += 18;
    });
  }

  // ── Footer on each page ───────────────────────────────────────────────────

  const totalPages = (doc as unknown as { bufferedPageRange(): { start: number; count: number } }).bufferedPageRange();
  for (let i = 0; i < totalPages.count; i++) {
    doc.switchToPage(totalPages.start + i);
    doc.fontSize(8).fillColor(GRAY_400).text(
      `CVOW Handover Pack — ${input.stringName} — ${formatDate(input.generatedAt)}   ·   Page ${i + 1} of ${totalPages.count}`,
      50,
      doc.page.height - 30,
      { width: W, align: "center" },
    );
  }

  doc.end();
  return Buffer.concat(chunks);
}
