import { Router, type IRouter } from "express";
import { eq, inArray } from "drizzle-orm";
import { db, documentsTable, phasesTable, imagesTable, issuesTable, locationsTable } from "@workspace/db";
import {
  ListDocumentsQueryParams,
  ListDocumentsResponse,
  GenerateDocumentBody,
  GetDocumentParams,
  GetDocumentResponse,
  DownloadDocumentParams,
} from "@workspace/api-zod";
import { serialize } from "../lib/serialize";

const router: IRouter = Router();

router.get("/documents", async (req, res): Promise<void> => {
  const queryParams = ListDocumentsQueryParams.safeParse(req.query);
  let documents;
  if (queryParams.success && queryParams.data.phaseId) {
    documents = await db.select().from(documentsTable).where(eq(documentsTable.phaseId, queryParams.data.phaseId));
  } else {
    documents = await db.select().from(documentsTable);
  }
  res.json(ListDocumentsResponse.parse(serialize(documents)));
});

router.post("/documents/generate", async (req, res): Promise<void> => {
  const parsed = GenerateDocumentBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: parsed.error.message });
    return;
  }
  const { phaseId, generatedBy, title } = parsed.data;
  const [phase] = await db.select().from(phasesTable).where(eq(phasesTable.id, phaseId));
  if (!phase) {
    res.status(400).json({ error: "Phase not found" });
    return;
  }
  if (phase.status !== "complete") {
    res.status(400).json({ error: "Phase must be approved/complete before generating a document" });
    return;
  }
  const [location] = await db.select().from(locationsTable).where(eq(locationsTable.id, phase.locationId));
  const images = await db.select().from(imagesTable).where(eq(imagesTable.phaseId, phaseId));
  const imageIds = images.map((i) => i.id);
  let allIssues: { severity: string; type: string; description: string; resolved: boolean }[] = [];
  if (imageIds.length > 0) {
    allIssues = await db.select({
      severity: issuesTable.severity,
      type: issuesTable.type,
      description: issuesTable.description,
      resolved: issuesTable.resolved,
    }).from(issuesTable).where(inArray(issuesTable.imageId, imageIds));
  }
  const approvedImages = images.filter((i) => i.reviewStatus === "approved");
  const rejectedImages = images.filter((i) => i.reviewStatus === "rejected");
  const criticalIssues = allIssues.filter((i) => i.severity === "critical" && !i.resolved);

  const docTitle = title ?? `Phase Completion Report — ${phase.phaseType}`;
  const generatedAt = new Date().toISOString();
  const content = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>${docTitle}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #1a1a2e; }
    h1 { color: #1a1a2e; border-bottom: 2px solid #3b82f6; padding-bottom: 8px; }
    h2 { color: #2d3748; margin-top: 32px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; }
    th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; font-size: 14px; }
    th { background: #f7fafc; font-weight: 600; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 12px; font-weight: 600; }
    .critical { background: #fed7d7; color: #c53030; }
    .warning { background: #fefcbf; color: #b7791f; }
    .info { background: #bee3f8; color: #2b6cb0; }
    .approved { background: #c6f6d5; color: #276749; }
    .rejected { background: #fed7d7; color: #c53030; }
    .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin: 16px 0; }
    .summary-card { background: #f7fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; text-align: center; }
    .summary-card .value { font-size: 28px; font-weight: 700; color: #2d3748; }
    .summary-card .label { font-size: 13px; color: #718096; margin-top: 4px; }
    .meta { color: #718096; font-size: 13px; margin-bottom: 8px; }
  </style>
</head>
<body>
  <h1>${docTitle}</h1>
  <p class="meta">Generated: ${generatedAt} | Generated by: ${generatedBy}</p>
  <p class="meta">Phase Type: <strong>${phase.phaseType}</strong> | Status: <strong>${phase.status}</strong> | Location: <strong>${location?.name ?? "Unknown"} (${location?.type ?? ""})</strong></p>
  ${phase.approvedBy ? `<p class="meta">Approved by: <strong>${phase.approvedBy}</strong> on ${phase.approvedAt ? new Date(phase.approvedAt).toLocaleString() : "N/A"}</p>` : ""}

  <h2>Summary</h2>
  <div class="summary-grid">
    <div class="summary-card"><div class="value">${images.length}</div><div class="label">Total Images</div></div>
    <div class="summary-card"><div class="value">${approvedImages.length}</div><div class="label">Approved</div></div>
    <div class="summary-card"><div class="value">${rejectedImages.length}</div><div class="label">Rejected</div></div>
    <div class="summary-card"><div class="value">${allIssues.length}</div><div class="label">Total Issues</div></div>
    <div class="summary-card"><div class="value">${criticalIssues.length}</div><div class="label">Critical Issues</div></div>
    <div class="summary-card"><div class="value">${allIssues.filter(i => i.resolved).length}</div><div class="label">Resolved Issues</div></div>
  </div>

  <h2>Image Records (${images.length})</h2>
  <table>
    <thead><tr><th>#</th><th>Filename</th><th>Uploaded By</th><th>Uploaded At</th><th>Review Status</th><th>Reviewed By</th></tr></thead>
    <tbody>
      ${images.map((img, idx) => `
      <tr>
        <td>${idx + 1}</td>
        <td>${img.filename ?? img.driveFileId ?? `Image ${img.id}`}</td>
        <td>${img.uploadedBy ?? "—"}</td>
        <td>${new Date(img.uploadedAt).toLocaleString()}</td>
        <td><span class="badge ${img.reviewStatus}">${img.reviewStatus}</span></td>
        <td>${img.reviewedBy ?? "—"}</td>
      </tr>`).join("")}
    </tbody>
  </table>

  ${allIssues.length > 0 ? `
  <h2>Issues (${allIssues.length})</h2>
  <table>
    <thead><tr><th>Severity</th><th>Type</th><th>Description</th><th>Status</th></tr></thead>
    <tbody>
      ${allIssues.map((issue) => `
      <tr>
        <td><span class="badge ${issue.severity}">${issue.severity}</span></td>
        <td>${issue.type}</td>
        <td>${issue.description}</td>
        <td>${issue.resolved ? "Resolved" : "Open"}</td>
      </tr>`).join("")}
    </tbody>
  </table>
  ` : "<h2>Issues</h2><p>No issues recorded.</p>"}

  <hr style="margin-top:40px; border-color: #e2e8f0;" />
  <p style="color:#718096; font-size:12px;">This document was auto-generated by the Installation Image Review System.</p>
</body>
</html>`;

  const [doc] = await db.insert(documentsTable).values({
    phaseId,
    generatedBy,
    title: docTitle,
    content,
    generatedAt: new Date(),
  }).returning();

  res.status(201).json(GetDocumentResponse.parse(serialize(doc)));
});

router.get("/documents/:id", async (req, res): Promise<void> => {
  const params = GetDocumentParams.safeParse(req.params);
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }
  const [doc] = await db.select().from(documentsTable).where(eq(documentsTable.id, params.data.id));
  if (!doc) {
    res.status(404).json({ error: "Document not found" });
    return;
  }
  res.json(GetDocumentResponse.parse(serialize(doc)));
});

router.get("/documents/:id/download", async (req, res): Promise<void> => {
  const params = DownloadDocumentParams.safeParse(req.params);
  if (!params.success) {
    res.status(400).json({ error: params.error.message });
    return;
  }
  const [doc] = await db.select().from(documentsTable).where(eq(documentsTable.id, params.data.id));
  if (!doc) {
    res.status(404).json({ error: "Document not found" });
    return;
  }
  res.setHeader("Content-Type", "text/html");
  res.setHeader("Content-Disposition", `attachment; filename="${doc.title.replace(/[^a-zA-Z0-9-_]/g, "_")}.html"`);
  res.send(doc.content ?? "<html><body><p>No content</p></body></html>");
});

export default router;
