// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dpr-filters/FilterPills.tsx": () => import("../components/mockups/dpr-filters/FilterPills.tsx"),
  "./components/mockups/dpr-filters/FilterPillsStatus.tsx": () => import("../components/mockups/dpr-filters/FilterPillsStatus.tsx")
};
