// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/capture-redesign/After.tsx": () => import("../components/mockups/capture-redesign/After.tsx"),
  "./components/mockups/capture-redesign/Before.tsx": () => import("../components/mockups/capture-redesign/Before.tsx"),
  "./components/mockups/dpr-filters/FilterPills.tsx": () => import("../components/mockups/dpr-filters/FilterPills.tsx"),
  "./components/mockups/dpr-filters/FilterPillsStatus.tsx": () => import("../components/mockups/dpr-filters/FilterPillsStatus.tsx"),
  "./components/mockups/capture-client/EmptyState.tsx": () => import("../components/mockups/capture-client/EmptyState.tsx"),
  "./components/mockups/capture-client/FilledState.tsx": () => import("../components/mockups/capture-client/FilledState.tsx"),
  "./components/mockups/team-calendar/TeamLocationCalendar.tsx": () => import("../components/mockups/team-calendar/TeamLocationCalendar.tsx")
};
