import PDFDocument from "pdfkit";

export interface HandoverPhotoWithBuffer {
  photoId: string;
  cableLink: string | null;
  phaseLink: string | null;
  reqImgType: string | null;
  reqImgOrder: string | null;
  approval: string | null;
  label: string | null;
  imageBuffer: Buffer | null;
}

export interface HandoverReport {
  name: string;
  reportType: string;
  cable: string | null;
  string: string;
}

export interface HandoverPackInput {
  stringName: string;
  ospName: string;
  generatedBy: string;
  generatedAt: Date;
  photos: HandoverPhotoWithBuffer[];
  reports: HandoverReport[];
}

const BRAND_BLUE  = "#1e3a5f";
const BRAND_LIGHT = "#e8f0f8";
const GRAY_700    = "#374151";
const GRAY_400    = "#9ca3af";
const GREEN       = "#166534";
const RED         = "#991b1b";
const AMBER       = "#92400e";

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
}

const REPORT_TYPE_COLORS: Record<string, string> = {
  "As-Found":               "#2b6cb0",
  "As-Left":                "#276749",
  "Completion Check":       "#553c9a",
  "FO Termination":         "#c05621",
  "ICCP":                   "#744210",
  "Pull-in Preparation":    "#086f83",
  "Temporary Hang Off":     "#9b2c2c",
  "Permanent Hang Off":     "#822727",
  "Cable Pull-in":          "#234e52",
  "Termination Completion": "#2c5282",
};

export function generateHandoverPdf(input: HandoverPackInput): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
  const chunks: Buffer[] = [];
  const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true });
  doc.on("data", (c: Buffer) => chunks.push(c));
  doc.on("error", reject);
  doc.on("end", () => resolve(Buffer.concat(chunks)));

  const W = doc.page.width - 100;

  // ── Cover page ─────────────────────────────────────────────────────────────

  doc.rect(50, 50, W, 5).fill(BRAND_BLUE);

  doc.fontSize(24).fillColor(BRAND_BLUE).text("CVOW Installation Handover Pack", 50, 70, { width: W, align: "center" });
  doc.fontSize(16).fillColor(GRAY_700).text(`String ${input.stringName}`, 50, 104, { width: W, align: "center" });
  doc.fontSize(11).fillColor(GRAY_400).text(`OSP: ${input.ospName}`, 50, 127, { width: W, align: "center" });

  doc.fontSize(10).fillColor(GRAY_400).text(
    `Generated: ${formatDate(input.generatedAt)}   ·   Generated by: ${input.generatedBy}`,
    50, 148, { width: W, align: "center" },
  );

  const boxY = 178;
  const boxW = (W - 20) / 3;
  const boxes = [
    { label: "Approved Photos", value: String(input.photos.length) },
    { label: "Field Reports", value: String(input.reports.length) },
    { label: "Cables / Towers", value: String(new Set(input.photos.map(p => p.cableLink).filter(Boolean)).size) },
  ];
  boxes.forEach((box, i) => {
    const x = 50 + i * (boxW + 10);
    doc.rect(x, boxY, boxW, 65).fillAndStroke(BRAND_LIGHT, BRAND_BLUE);
    doc.fontSize(26).fillColor(BRAND_BLUE).text(box.value, x, boxY + 8, { width: boxW, align: "center" });
    doc.fontSize(9).fillColor(GRAY_700).text(box.label, x, boxY + 42, { width: boxW, align: "center" });
  });

  doc.rect(50, boxY + 80, W, 1).fill(GRAY_400);

  doc.fontSize(9).fillColor(GRAY_700).text(
    "This handover pack was automatically generated by the CVOW Installation Image Review System. " +
    "It includes all approved installation photos and associated field reports for the string listed above.",
    50, boxY + 92, { width: W },
  );

  // ── Photo section ──────────────────────────────────────────────────────────

  const photosWithImage = input.photos.filter(p => p.imageBuffer !== null);
  const photosWithoutImage = input.photos.filter(p => p.imageBuffer === null);

  if (input.photos.length === 0) {
    doc.addPage();
    doc.fontSize(14).fillColor(BRAND_BLUE).text("Approved Photos", 50, 50);
    doc.rect(50, 70, W, 2).fill(BRAND_BLUE);
    doc.fontSize(10).fillColor(GRAY_400).text("No approved photos found for this string.", 50, 84);
  } else {
    // Images: 2-column grid, 3 rows per page = 6 photos per page
    if (photosWithImage.length > 0) {
      doc.addPage();
      doc.fontSize(14).fillColor(BRAND_BLUE).text(`Approved Photos (${photosWithImage.length} with images)`, 50, 50);
      doc.rect(50, 70, W, 2).fill(BRAND_BLUE);

      const colW = (W - 10) / 2;
      const imgH = 170;
      const captionH = 28;
      const rowH = imgH + captionH + 10;
      let imgY = 82;
      let pageIdx = 0;

      photosWithImage.forEach((photo, i) => {
        const col = i % 2;
        if (i > 0 && i % 6 === 0) {
          doc.addPage();
          doc.fontSize(11).fillColor(BRAND_BLUE).text(`Approved Photos (continued)`, 50, 30);
          imgY = 55;
          pageIdx = 0;
        }
        if (i > 0 && i % 2 === 0 && i % 6 !== 0) {
          imgY += rowH;
          pageIdx++;
        }

        const x = 50 + col * (colW + 10);

        // Draw image
        try {
          doc.image(photo.imageBuffer!, x, imgY, { width: colW, height: imgH, fit: [colW, imgH], align: "center", valign: "center" });
        } catch {
          doc.rect(x, imgY, colW, imgH).fillAndStroke(BRAND_LIGHT, GRAY_400);
          doc.fontSize(8).fillColor(GRAY_400).text("Image unavailable", x, imgY + imgH / 2 - 5, { width: colW, align: "center" });
        }

        // Caption bar
        const capY = imgY + imgH + 2;
        doc.rect(x, capY, colW, captionH - 4).fill(BRAND_BLUE);

        const approval = (photo.approval ?? "").toLowerCase();
        const approvalColor = approval === "approved" || approval === "checked" || approval === "verified" ? GREEN : approval === "rejected" ? RED : AMBER;

        doc.fontSize(7).fillColor("white")
          .text(photo.cableLink ?? "—", x + 3, capY + 2, { width: colW * 0.55, lineBreak: false })
          .text(photo.reqImgType ?? photo.label ?? "—", x + 3, capY + 11, { width: colW * 0.75, lineBreak: false });
        doc.fontSize(7).fillColor(approvalColor)
          .text(photo.approval ?? "Pending", x + colW * 0.72, capY + 6, { width: colW * 0.28, align: "right", lineBreak: false });
      });
    }

    // Photo manifest table (ALL approved photos including those without images)
    doc.addPage();
    doc.fontSize(14).fillColor(BRAND_BLUE).text("Photo Manifest", 50, 50);
    doc.rect(50, 70, W, 2).fill(BRAND_BLUE);

    const colWidths = [28, 140, 130, 115, 65];
    const colX      = [50, 78, 218, 348, 463];
    const headers   = ["#", "Cable / Tower", "Phase", "Image Type", "Approval"];

    let y = 82;

    const drawHeader = () => {
      doc.rect(50, y, W, 17).fill(BRAND_BLUE);
      headers.forEach((h, i) => {
        doc.fontSize(8).fillColor("white").text(h, colX[i] + 2, y + 5, { width: colWidths[i], lineBreak: false });
      });
      y += 17;
    };
    drawHeader();

    input.photos.forEach((p, idx) => {
      if (y > doc.page.height - 70) {
        doc.addPage();
        y = 50;
        drawHeader();
      }
      doc.rect(50, y, W, 16).fill(idx % 2 === 0 ? "#f9fafb" : "white");

      const approval = (p.approval ?? "").toLowerCase();
      const approvalFg = approval === "approved" || approval === "checked" || approval === "verified" ? GREEN : approval === "rejected" ? RED : AMBER;

      doc.fontSize(7.5).fillColor(GRAY_700)
        .text(String(idx + 1),               colX[0] + 2, y + 4, { width: colWidths[0], lineBreak: false })
        .text(p.cableLink ?? "—",             colX[1] + 2, y + 4, { width: colWidths[1], lineBreak: false })
        .text(p.phaseLink ?? "—",             colX[2] + 2, y + 4, { width: colWidths[2], lineBreak: false })
        .text(p.reqImgType ?? p.label ?? "—", colX[3] + 2, y + 4, { width: colWidths[3], lineBreak: false });
      doc.fontSize(7.5).fillColor(approvalFg)
        .text(p.approval ?? "Pending",        colX[4] + 2, y + 4, { width: colWidths[4], lineBreak: false });

      y += 16;
    });
  }

  // ── Reports section ────────────────────────────────────────────────────────

  doc.addPage();
  doc.fontSize(14).fillColor(BRAND_BLUE).text("Field Reports", 50, 50);
  doc.rect(50, 70, W, 2).fill(BRAND_BLUE);

  if (input.reports.length === 0) {
    doc.fontSize(10).fillColor(GRAY_400).text("No field reports found for this string.", 50, 84);
  } else {
    const colW2 = [105, 115, 275];
    const colX2 = [50, 155, 270];
    const hdrs2 = ["Cable / Tower", "Type", "Report Name"];

    let y2 = 82;
    const drawHdr2 = () => {
      doc.rect(50, y2, W, 17).fill(BRAND_BLUE);
      hdrs2.forEach((h, i) => {
        doc.fontSize(8).fillColor("white").text(h, colX2[i] + 2, y2 + 5, { width: colW2[i], lineBreak: false });
      });
      y2 += 17;
    };
    drawHdr2();

    input.reports.forEach((r, idx) => {
      if (y2 > doc.page.height - 70) {
        doc.addPage();
        y2 = 50;
        drawHdr2();
      }
      doc.rect(50, y2, W, 16).fill(idx % 2 === 0 ? "#f9fafb" : "white");

      const typeColor = REPORT_TYPE_COLORS[r.reportType] ?? GRAY_700;

      doc.fontSize(7.5).fillColor(GRAY_700)
        .text(r.cable ?? r.string, colX2[0] + 2, y2 + 4, { width: colW2[0], lineBreak: false });
      doc.fontSize(7.5).fillColor(typeColor)
        .text(r.reportType, colX2[1] + 2, y2 + 4, { width: colW2[1], lineBreak: false });
      doc.fontSize(7.5).fillColor(GRAY_700)
        .text(r.name, colX2[2] + 2, y2 + 4, { width: colW2[2], lineBreak: false });

      y2 += 16;
    });
  }

  // ── Page footers ───────────────────────────────────────────────────────────

  const range = (doc as unknown as { bufferedPageRange(): { start: number; count: number } }).bufferedPageRange();
  for (let i = 0; i < range.count; i++) {
    doc.switchToPage(range.start + i);
    doc.fontSize(7.5).fillColor(GRAY_400).text(
      `CVOW Handover Pack — OSP ${input.ospName} / String ${input.stringName} — ${formatDate(input.generatedAt)}   ·   Page ${i + 1} of ${range.count}`,
      50, doc.page.height - 28, { width: W, align: "center" },
    );
  }

  doc.end();
  }); // end Promise
}
