import PDFDocument from "pdfkit";
import type { ReportTemplate, ChecklistGroup, ChecklistItem } from "./report-templates.js";

const BRAND_BLUE  = "#1e3a5f";
const BRAND_LIGHT = "#e8f0f8";
const GRAY_700    = "#374151";
const GRAY_500    = "#6b7280";
const GRAY_300    = "#d1d5db";
const GREEN       = "#166534";
const RED         = "#991b1b";

export interface ChecklistResponse {
  response: "Yes" | "No" | "N/A" | "";
  comment?: string;
}

export interface PhaseRowData {
  [columnKey: string]: string;
}

export interface FieldReportFormData {
  header: Record<string, string>;
  phases?: Record<string, PhaseRowData>;          // rowKey → {colKey: value}
  checklist: Record<string, ChecklistResponse>;   // itemKey → response
  numericFields?: Record<string, string>;
  remarks?: string;
}

export interface FieldReportPdfImage {
  index:   number;
  caption: string;
  buffer:  Buffer;
}

export interface FieldReportPdfInput {
  template: ReportTemplate;
  data: FieldReportFormData;
  generatedBy: string;
  generatedAt: Date;
  /** One entry per uploaded image. Captions/order match template.imagePlaceholders. */
  images?: FieldReportPdfImage[];
}

export function generateFieldReportPdf(input: FieldReportPdfInput): Promise<Buffer> {
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    const doc = new PDFDocument({ size: "A4", margin: 50, bufferPages: true });
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("error", reject);
    doc.on("end", () => resolve(Buffer.concat(chunks)));

    try {
      render(doc, input);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

function render(doc: PDFKit.PDFDocument, input: FieldReportPdfInput): void {
  const { template, data } = input;

  // Title bar
  doc.rect(50, 50, 495, 36).fill(BRAND_BLUE);
  doc.fillColor("#fff").fontSize(15).font("Helvetica-Bold")
     .text(template.documentTitle, 60, 60, { width: 475 });
  doc.fillColor(GRAY_700);
  doc.moveDown(2);

  // Header table
  drawHeaderTable(doc, template, data.header);

  // Document references
  if (template.documentRefs && template.documentRefs.length > 0) {
    doc.moveDown(0.6);
    sectionTitle(doc, "Document References");
    drawTwoColTable(doc, [
      ["Document Name(s)",   template.documentRefs.map(r => r.name).join("\n")],
      ["Document Number(s)", template.documentRefs.map(r => r.number ?? "—").join("\n")],
    ]);
  }

  // Phases table
  if (template.phases) {
    doc.moveDown(0.6);
    sectionTitle(doc, template.phases.title);
    drawPhaseTable(doc, template.phases.rows, template.phases.columns, data.phases ?? {});
  }

  // Checklists
  for (const group of template.checklists) {
    if (group.items.length === 0) continue;
    doc.moveDown(0.6);
    if (group.title) sectionTitle(doc, group.title);
    drawChecklistTable(doc, group, data.checklist);
  }

  // Numeric fields
  if (template.numericFields && template.numericFields.length > 0) {
    doc.moveDown(0.6);
    sectionTitle(doc, "Recorded Values");
    const rows: [string, string][] = template.numericFields.map(f => {
      const v = data.numericFields?.[f.key] ?? "";
      return [f.label, v ? `${v}${f.unit ? " " + f.unit : ""}` : "—"];
    });
    drawTwoColTable(doc, rows);
  }

  // Image placeholders — embed any uploaded images, list missing ones as captions.
  if (template.imagePlaceholders && template.imagePlaceholders.length > 0) {
    doc.moveDown(0.6);
    sectionTitle(doc, "Required Images");

    const imagesByIndex = new Map<number, FieldReportPdfImage>();
    for (const img of input.images ?? []) imagesByIndex.set(img.index, img);

    drawImageGrid(doc, template.imagePlaceholders, imagesByIndex);
  }

  // Remarks
  if (template.hasRemarks && data.remarks && data.remarks.trim()) {
    doc.moveDown(0.6);
    sectionTitle(doc, "Remarks");
    doc.fontSize(10).fillColor(GRAY_700).text(data.remarks, 60, doc.y, { width: 485 });
  }

  // Footer signature line
  doc.moveDown(2);
  ensureSpace(doc, 60);
  doc.strokeColor(GRAY_300).lineWidth(0.5).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.4);
  doc.fontSize(9).fillColor(GRAY_500)
     .text(`Generated by ${input.generatedBy} on ${input.generatedAt.toLocaleString("en-GB")}`, 50, doc.y);
  doc.text(`Manually-created field report — Installation Image Review System`, 50, doc.y);
}

// ── Layout helpers ──

function ensureSpace(doc: PDFKit.PDFDocument, h: number): void {
  if (doc.y + h > doc.page.height - 60) doc.addPage();
}

function drawImageGrid(
  doc: PDFKit.PDFDocument,
  captions: string[],
  imagesByIndex: Map<number, FieldReportPdfImage>,
): void {
  const totalW = 495;
  const gap    = 10;
  const colW   = (totalW - gap) / 2;
  const imgH   = 170;
  const capH   = 32;
  const cellH  = imgH + capH;

  for (let i = 0; i < captions.length; i++) {
    const col = i % 2;
    if (col === 0) {
      ensureSpace(doc, cellH + 10);
      // Remember row top so the right cell aligns with the left.
      (doc as unknown as { __rowTop?: number }).__rowTop = doc.y;
    }
    const rowTop = (doc as unknown as { __rowTop?: number }).__rowTop ?? doc.y;
    const x = 50 + col * (colW + gap);
    const y = rowTop;

    const img = imagesByIndex.get(i);
    if (img) {
      try {
        doc.image(img.buffer, x, y, { fit: [colW, imgH], align: "center", valign: "center" });
      } catch {
        drawMissing(doc, x, y, colW, imgH, "Could not render image");
      }
    } else {
      drawMissing(doc, x, y, colW, imgH, "No image uploaded");
    }

    // Caption block
    const capY = y + imgH + 2;
    doc.rect(x, capY, colW, capH - 4).fillAndStroke(BRAND_LIGHT, GRAY_300);
    doc.fillColor(BRAND_BLUE).fontSize(7).font("Helvetica-Bold")
       .text(`Image ${i + 1}`, x + 4, capY + 3, { width: colW - 8 });
    doc.fillColor(GRAY_700).fontSize(8).font("Helvetica")
       .text(captions[i], x + 4, capY + 12, { width: colW - 8, height: capH - 16, ellipsis: true });

    // After the right cell (or the last cell if odd count), drop the cursor below the row.
    if (col === 1 || i === captions.length - 1) {
      doc.y = y + cellH + 6;
    }
  }
  doc.fillColor(GRAY_700).font("Helvetica");
}

function drawMissing(doc: PDFKit.PDFDocument, x: number, y: number, w: number, h: number, label: string): void {
  doc.rect(x, y, w, h).fillAndStroke(BRAND_LIGHT, GRAY_300);
  doc.fillColor(GRAY_500).fontSize(9).font("Helvetica")
     .text(label, x, y + h / 2 - 5, { width: w, align: "center" });
}

function sectionTitle(doc: PDFKit.PDFDocument, text: string): void {
  ensureSpace(doc, 24);
  doc.fillColor(BRAND_BLUE).fontSize(11).font("Helvetica-Bold")
     .text(text, 50, doc.y);
  doc.moveTo(50, doc.y + 1).lineTo(545, doc.y + 1).strokeColor(BRAND_BLUE).lineWidth(0.5).stroke();
  doc.moveDown(0.4);
  doc.fillColor(GRAY_700).font("Helvetica");
}

function drawHeaderTable(doc: PDFKit.PDFDocument, template: ReportTemplate, header: Record<string, string>): void {
  const labelW = 150;
  const valW   = 345;
  for (const f of template.header) {
    const value = (header[f.key] ?? f.defaultValue ?? "").toString();
    const valueLines = doc.fontSize(10).font("Helvetica").heightOfString(value || "—", { width: valW - 10 });
    const rowH = Math.max(20, valueLines + 8);
    ensureSpace(doc, rowH);
    const y = doc.y;
    doc.rect(50, y, labelW, rowH).fillAndStroke(BRAND_LIGHT, GRAY_300);
    doc.rect(50 + labelW, y, valW, rowH).fillAndStroke("#ffffff", GRAY_300);
    doc.fillColor(BRAND_BLUE).fontSize(9).font("Helvetica-Bold")
       .text(f.label, 55, y + 5, { width: labelW - 10 });
    doc.fillColor(GRAY_700).fontSize(10).font("Helvetica")
       .text(value || "—", 55 + labelW, y + 5, { width: valW - 10 });
    doc.y = y + rowH;
  }
}

function drawTwoColTable(doc: PDFKit.PDFDocument, rows: [string, string][]): void {
  const labelW = 200;
  const valW   = 295;
  for (const [label, value] of rows) {
    const valueH = doc.fontSize(10).font("Helvetica").heightOfString(value || "—", { width: valW - 10 });
    const rowH = Math.max(20, valueH + 8);
    ensureSpace(doc, rowH);
    const y = doc.y;
    doc.rect(50, y, labelW, rowH).fillAndStroke(BRAND_LIGHT, GRAY_300);
    doc.rect(50 + labelW, y, valW, rowH).fillAndStroke("#ffffff", GRAY_300);
    doc.fillColor(BRAND_BLUE).fontSize(9).font("Helvetica-Bold")
       .text(label, 55, y + 5, { width: labelW - 10 });
    doc.fillColor(GRAY_700).fontSize(10).font("Helvetica")
       .text(value || "—", 55 + labelW, y + 5, { width: valW - 10 });
    doc.y = y + rowH;
  }
}

function drawPhaseTable(
  doc: PDFKit.PDFDocument,
  rows: { key: string; label: string }[],
  columns: { key: string; label: string }[],
  data: Record<string, PhaseRowData>,
): void {
  const tableW = 495;
  const phaseW = 80;
  const colW = (tableW - phaseW) / columns.length;

  // Header row
  ensureSpace(doc, 22);
  let y = doc.y;
  doc.rect(50, y, phaseW, 22).fillAndStroke(BRAND_BLUE, BRAND_BLUE);
  doc.fillColor("#fff").fontSize(9).font("Helvetica-Bold").text("Phase", 55, y + 7, { width: phaseW - 10 });
  for (let i = 0; i < columns.length; i++) {
    doc.rect(50 + phaseW + i * colW, y, colW, 22).fillAndStroke(BRAND_BLUE, BRAND_BLUE);
    doc.fillColor("#fff").text(columns[i].label, 55 + phaseW + i * colW, y + 7, { width: colW - 10 });
  }
  doc.y = y + 22;

  for (const r of rows) {
    const row = data[r.key] ?? {};
    const heights = columns.map(c => doc.fontSize(9).font("Helvetica").heightOfString(row[c.key] || "—", { width: colW - 10 }));
    const rowH = Math.max(20, ...heights) + 8;
    ensureSpace(doc, rowH);
    y = doc.y;
    doc.rect(50, y, phaseW, rowH).fillAndStroke(BRAND_LIGHT, GRAY_300);
    doc.fillColor(BRAND_BLUE).fontSize(9).font("Helvetica-Bold").text(r.label, 55, y + 5, { width: phaseW - 10 });
    for (let i = 0; i < columns.length; i++) {
      doc.rect(50 + phaseW + i * colW, y, colW, rowH).fillAndStroke("#fff", GRAY_300);
      doc.fillColor(GRAY_700).fontSize(9).font("Helvetica")
         .text(row[columns[i].key] || "—", 55 + phaseW + i * colW, y + 5, { width: colW - 10 });
    }
    doc.y = y + rowH;
  }
}

function drawChecklistTable(
  doc: PDFKit.PDFDocument,
  group: ChecklistGroup,
  responses: Record<string, ChecklistResponse>,
): void {
  const tableW = 495;
  const itemW  = 290;
  const respW  = 50;
  const commW  = tableW - itemW - respW;

  // Header
  ensureSpace(doc, 22);
  let y = doc.y;
  doc.rect(50, y, itemW, 22).fillAndStroke(BRAND_BLUE, BRAND_BLUE);
  doc.fillColor("#fff").fontSize(9).font("Helvetica-Bold").text("Item", 55, y + 7, { width: itemW - 10 });
  doc.rect(50 + itemW, y, respW, 22).fillAndStroke(BRAND_BLUE, BRAND_BLUE);
  doc.text("Response", 55 + itemW, y + 7, { width: respW - 10, align: "center" });
  doc.rect(50 + itemW + respW, y, commW, 22).fillAndStroke(BRAND_BLUE, BRAND_BLUE);
  doc.text("Comments", 55 + itemW + respW, y + 7, { width: commW - 10 });
  doc.y = y + 22;

  for (const item of group.items) {
    drawChecklistRow(doc, item, responses[item.key], itemW, respW, commW);
  }
}

function drawChecklistRow(
  doc: PDFKit.PDFDocument,
  item: ChecklistItem,
  resp: ChecklistResponse | undefined,
  itemW: number,
  respW: number,
  commW: number,
): void {
  const r = resp?.response ?? "";
  const c = resp?.comment ?? "";
  const itemH = doc.fontSize(9).font("Helvetica").heightOfString(item.label, { width: itemW - 10 });
  const commH = doc.fontSize(9).font("Helvetica").heightOfString(c || " ", { width: commW - 10 });
  const rowH = Math.max(20, itemH, commH) + 8;
  ensureSpace(doc, rowH);
  const y = doc.y;
  doc.rect(50, y, itemW, rowH).fillAndStroke("#fff", GRAY_300);
  doc.rect(50 + itemW, y, respW, rowH).fillAndStroke("#fff", GRAY_300);
  doc.rect(50 + itemW + respW, y, commW, rowH).fillAndStroke("#fff", GRAY_300);

  doc.fillColor(GRAY_700).fontSize(9).font("Helvetica").text(item.label, 55, y + 5, { width: itemW - 10 });

  let badgeColor = GRAY_500;
  let badgeText = "—";
  if (r === "Yes") { badgeColor = GREEN; badgeText = "✔"; }
  else if (r === "No") { badgeColor = RED; badgeText = "✘"; }
  else if (r === "N/A") { badgeColor = GRAY_500; badgeText = "N/A"; }
  doc.fillColor(badgeColor).fontSize(13).font("Helvetica-Bold")
     .text(badgeText, 55 + itemW, y + 4, { width: respW - 10, align: "center" });

  doc.fillColor(GRAY_700).fontSize(9).font("Helvetica").text(c || "", 55 + itemW + respW, y + 5, { width: commW - 10 });
  doc.y = y + rowH;
}
